# Generated by Django 3.2.7 on 2021-09-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coremodel',
            name='cpf',
            field=models.CharField(default='', max_length=11),
        ),
    ]
